version:  '3.2'

services:
  db:
    image: "postgres"
    networks:
      - spring
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cars
    ports:
      - 5432:5432

networks:
  spring: